name: Collab check
on: [pull_request]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@master
    - name: Run action
      id: collab-check
      env:
        PR_NUMBER: ${{ github.event.number }}
        AUTHORIZED: ${{ secrets.AUTHORIZED }}
      uses: chentex/collab-check@master
